#!/system/bin/sh
#=======================================#
#VARIABLES===============================#
BB=/data/adb/magisk/busybox
CLOG=/data/media/0/YourBLchanges.log
ZLOG=/data/media/0/YourBLchanges.log
BRANCH="5-Disable-EU-compatible-mode"
#=======================================#
#=======================================#

kmsg3() {
	echo -e "[*] $@" >> $CLOG
}

sleep 1

$BB cp -rf /data/adb/modules/butterlimitsforop7poos11uni/bl1.sh /data/adb/modules/butterlimitsforop7poos11uni/bl.sh
$BB cp -rf /data/adb/modules/butterlimitsforop7poos11uni/zbloff1.sh /data/adb/modules/butterlimitsforop7poos11uni/zbloff.sh
$BB cp -rf /data/adb/modules/butterlimitsforop7poos11uni/zbboff1.sh /data/adb/modules/butterlimitsforop7poos11uni/zbboff.sh
$BB cp -rf /data/adb/modules/butterlimitsforop7poos11uni/zon1.sh /data/adb/modules/butterlimitsforop7poos11uni/zon.sh
$BB cp -rf /data/adb/modules/butterlimitsforop7poos11uni/zbloff.sh /data/adb/modules/butterlimitsforop7poos11uni/post-fs-data.sh
$BB cp -rf /data/adb/modules/butterlimitsforop7poos11uni/blbb1.sh /data/adb/modules/butterlimitsforop7poos11uni/blbb.sh
$BB cp -rf /data/adb/modules/butterlimitsforop7poos11uni/blext1.sh /data/adb/modules/butterlimitsforop7poos11uni/blext.sh

$BB cp -rf /data/adb/modules/butterlimitsforop7poos11uni/service1.sh /data/adb/modules/butterlimitsforop7poos11uni/service.sh

$BB cp -rf /data/adb/modules/butterlimitsforop7poos11uni/system/etc/mkadp/bl/module.prop /data/adb/modules/butterlimitsforop7poos11uni
$BB cp -rf /data/adb/modules/butterlimitsforop7poos11uni/system/etc/mkadp/bl/system.prop /data/adb/modules/butterlimitsforop7poos11uni

$BB cp -rf /data/adb/modules/butterlimitsforop7poos11uni/system/etc/mkadp/bl/* /data/adb/modules/butterlimitsforop7poos11uni/system/etc/mkadp/


kmsg3 $(date)
kmsg3 "Disabled EU Compatible Mode"
kmsg3 "ButterLimits Enabled"
kmsg3 "----"

sleep 1

am start -a android.intent.action.MAIN -e toasttext "Disabled EU Compatible Mode. Rebooting device in 5 secs" -n mkadp.toast/.MainActivity

sleep 5

am start -a android.intent.action.MAIN -e toasttext "Rebooting Now..." -n mkadp.toast/.MainActivity

sleep 2

reboot
