#!/system/bin/sh
#=======================================#
#VARIABLES===============================#
BB=/data/adb/magisk/busybox
LOGZR=/data/media/0/blzram.log
LOG=/data/media/0/mkadp.log
MODE=/data/media/0/modeon.log
NEWLOG=/data/local/mkadp.log
NEWLOG2=/data/media/0/.mkadp.log
LOGFU=/data/media/0/butterlimits.log
CLOG=/data/media/0/YourBLchanges.log
BRANCH="9-Uninistall-ButterLimits-Completely"
#=======================================#
#=======================================#

$BB rm -rf $LOG
$BB rm -rf $MODE
$BB rm -rf $NEWLOG
$BB rm -rf $NEWLOG2
$BB rm -rf $LOGFU
$BB rm -rf $LOGZR
$BB rm -rf $CLOG
$BB rm -rf /data/adb/modules/butterlimitsforop7poos11uni/system/vendor/etc/mixer_paths_tavil.xml
sleep 1


$BB cp -rf /data/adb/modules/butterlimitsforop7poos11uni/system/etc/unbl/disable /data/adb/modules/butterlimitsforop7poos11uni/disable
$BB cp -rf /data/adb/modules/butterlimitsforop7poos11uni/system/etc/unbl/remove /data/adb/modules/butterlimitsforop7poos11uni/remove

sleep 5
reboot
